[package]
name = "logic_gates"
version = "0.1.0"
authors = ["lexi8821 <lexi@centrum.sk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
